name: Bug Report
description: Report a bug in MediaLLM
title: "[BUG]: "
labels: ["bug"]
body:
 - type: textarea
   id: description
   attributes:
     label: Bug Description
     description: What happened?
     placeholder: Clear and concise description of the bug
   validations:
     required: true

 - type: textarea
   id: reproduce
   attributes:
     label: Steps to Reproduce
     description: How can we reproduce this issue?
     placeholder: |
       1. Run 'mediallm ...'
       2. Use command '...'
       3. See error
   validations:
     required: true

 - type: input
   id: version
   attributes:
     label: Python Version
     placeholder: e.g., 3.11.0
   validations:
     required: true

 - type: input
   id: mediallm_version
   attributes:
     label: MediaLLM Version
     placeholder: e.g., 0.1.0
   validations:
     required: true

 - type: input
   id: ollama_version
   attributes:
     label: Ollama Version
     placeholder: e.g., 0.5.3
   validations:
     required: false

 - type: textarea
   id: error
   attributes:
     label: Error Message
     description: If applicable, paste the error message or traceback
     render: shell

 - type: textarea
   id: expected
   attributes:
     label: Expected Behavior
     description: What did you expect to happen?

 - type: textarea
   id: additional
   attributes:
     label: Additional Context
     description: Add any other context about the problem here
     placeholder: Media files, FFmpeg version, operating system, etc.