name: Feature Request
description: Suggest a new feature or enhancement for MediaLLM
title: "[FEATURE]: "
labels: ["enhancement"]
body:
 - type: textarea
   id: problem
   attributes:
     label: Problem Statement
     description: What problem does this feature solve?
     placeholder: Describe the problem or limitation you're facing with MediaLLM
   validations:
     required: true

 - type: textarea
   id: solution
   attributes:
     label: Proposed Solution
     description: What's your suggested solution?
     placeholder: Describe how you'd like this feature to work
   validations:
     required: true

 - type: textarea
   id: alternatives
   attributes:
     label: Alternatives Considered
     description: Have you considered any alternative solutions?
     placeholder: Any workarounds or different approaches?

 - type: dropdown
   id: feature_type
   attributes:
     label: Feature Type
     description: What type of feature is this?
     options:
       - New media format support
       - New conversion option
       - UI/UX improvement
       - Performance enhancement
       - Documentation improvement
       - Other
   validations:
     required: true

 - type: checkboxes
   id: checks
   attributes:
     label: Final Checklist
     options:
     - label: This feature would be useful to other users
       required: true
     - label: I'm willing to help implement this feature
       required: false
     - label: I've searched existing issues to avoid duplicates
       required: true