name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish_mediallm:
        description: 'Publish mediallm package'
        type: boolean
        default: true
      publish_mcp:
        description: 'Publish mediallm-mcp package'
        type: boolean
        default: true

jobs:
  publish-mediallm:
    if: github.event_name == 'release' || inputs.publish_mediallm
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: packages/mediallm
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Build package
      run: uv build
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: packages/mediallm/dist/

  publish-mcp:
    if: github.event_name == 'release' || inputs.publish_mcp
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: packages/mediallm-mcp
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Build package
      run: uv build
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: packages/mediallm-mcp/dist/