name: Release Both Packages

on:
  workflow_dispatch:
    inputs:
      publish_mediallm:
        description: 'Publish mediallm package'
        type: boolean
        default: true
      publish_mcp:
        description: 'Publish mediallm-mcp package'
        type: boolean
        default: true
      use_testpypi:
        description: 'Publish to TestPyPI instead'
        type: boolean
        default: false

permissions:
  id-token: write   # Required for trusted publishing
  contents: read    # Required to checkout code
  attestations: write # Required for attestations

jobs:
  publish-mediallm:
    name: Release MediaLLM
    if: inputs.publish_mediallm
    uses: ./.github/workflows/publish-mediallm.yml
    with:
      use_testpypi: ${{ inputs.use_testpypi }}
    permissions:
      id-token: write
      contents: read
      attestations: write

  publish-mcp:
    name: Release MediaLLM-MCP
    if: inputs.publish_mcp
    uses: ./.github/workflows/publish-mediallm-mcp.yml
    with:
      use_testpypi: ${{ inputs.use_testpypi }}
    permissions:
      id-token: write
      contents: read
      attestations: write